services:
  - type: web
    name: affair-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd AFFAIR && python manage.py migrate && gunicorn --chdir AFFAIR AFFAIR.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: AFFAIR.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: affair-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: affair-redis
          type: redis
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False"
      - key: PYTHONPATH
        value: "AFFAIR"

  - type: redis
    name: affair-redis
    ipAllowList: []

databases:
  - name: affair-db
    databaseName: affair
    user: affair
    plan: free 